- name: Create directories for configs
  file:
    path: "/opt/{{ item }}"
    state: directory
    recurse: yes
  loop:
    - prometheus
    - thanos
    - loki
    - grafana
    - grafana/dashboards
    - grafana/provisioning/dashboards

- name: Copy monitoring config files
  copy:
    src: "{{ item }}"
    dest: "/opt/{{ item | basename | regex_replace('\..*$', '') }}/{{ item }}"
  with_items:
    - thanos-config.yaml
    - loki-config.yaml
    - grafana-datasource.yaml

- name: Copy Grafana dashboard JSONs
  copy:
    src: node-dashboard.json
    dest: /opt/grafana/dashboards/node-dashboard.json

- name: Provision Grafana dashboard loader config
  copy:
    content: |
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          options:
            path: /var/lib/grafana/dashboards
    dest: /opt/grafana/provisioning/dashboards/dashboard.yaml

- name: Template Prometheus config with blue/green IPs
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart_policy: always

- name: Run Thanos Sidecar
  docker_container:
    name: thanos-sidecar
    image: improbable/thanos:latest
    command: sidecar --tsdb.path=/prometheus --prometheus.url=http://localhost:9090
    volumes:
      - /opt/prometheus:/prometheus
    restart_policy: always

- name: Run Loki container
  docker_container:
    name: loki
    image: grafana/loki
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - /opt/loki/loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"
    restart_policy: always

- name: Run Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - /opt/grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - /opt/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - /opt/grafana/dashboards:/var/lib/grafana/dashboards
    restart_policy: always

- name: Restart Prometheus to reload config
  docker_container:
    name: prometheus
    state: restarted
