---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker and dependencies
  apt:
    name:
      - docker.io
      - python3-pip
      - python3-apt
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to Docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3

- name: Install community.docker collection
  command: ansible-galaxy collection install community.docker
  changed_when: false
