---

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: true

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3

- name: Pull InventoWare Docker image
  community.docker.docker_image:
    name: your-dockerhub-user/inventoware-app
    source: pull

- name: Run InventoWare application container
  community.docker.docker_container:
    name: inventoware-app
    image: your-dockerhub-user/inventoware-app:latest
    state: started
    restart_policy: always
    published_ports:
      - "5000:5000"

- name: Run Node Exporter for monitoring
  community.docker.docker_container:
    name: node-exporter
    image: prom/node-exporter
    state: started
    restart_policy: always
    published_ports:
      - "9100:9100"
